language: php

sudo: false

php:
  - '7.3'
  - '7.4'

before_install:
  - composer self-update

install:
  - travis_retry composer update --prefer-dist

script:
  - ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
  - ./vendor/bin/phpunit -v

cache:
  directories:
    - $HOME/.composer/cache

after_success:
  - bash <(curl -s https://codecov.io/bash)
